USE DATABASE RETAIL_DATA_PLATFORM;

-- CDC: Streams capture row-level change metadata between offsets.
CREATE OR REPLACE STREAM SILVER.STRM_BRONZE_CSV_RAW ON TABLE BRONZE.BRONZE_SALES_CSV_RAW;
CREATE OR REPLACE STREAM SILVER.STRM_BRONZE_API_RAW ON TABLE BRONZE.BRONZE_SALES_API_RAW;
CREATE OR REPLACE STREAM SILVER.STRM_BRONZE_STREAM_RAW ON TABLE BRONZE.BRONZE_SALES_STREAM_RAW;

-- Optional inspection
-- SELECT * FROM SILVER.STRM_BRONZE_CSV_RAW;
