-- =============================================
-- 00_environment_setup.sql
-- Enterprise environment bootstrap for Retail Data Platform
-- =============================================

-- 1) Compute
CREATE OR REPLACE WAREHOUSE RETAIL_WH_XS
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE RETAIL_WH_ETL
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- 2) Security
CREATE OR REPLACE ROLE RETAIL_SYSADMIN;
CREATE OR REPLACE ROLE RETAIL_INGEST_ROLE;
CREATE OR REPLACE ROLE RETAIL_TRANSFORM_ROLE;
CREATE OR REPLACE ROLE RETAIL_BI_ROLE;

-- 3) Database + schemas (Medallion + Ops)
CREATE OR REPLACE DATABASE RETAIL_DATA_PLATFORM;
CREATE OR REPLACE SCHEMA RETAIL_DATA_PLATFORM.BRONZE;
CREATE OR REPLACE SCHEMA RETAIL_DATA_PLATFORM.SILVER;
CREATE OR REPLACE SCHEMA RETAIL_DATA_PLATFORM.GOLD;
CREATE OR REPLACE SCHEMA RETAIL_DATA_PLATFORM.MONITORING;
CREATE OR REPLACE SCHEMA RETAIL_DATA_PLATFORM.UTIL;

-- 4) Privileges
GRANT USAGE ON WAREHOUSE RETAIL_WH_ETL TO ROLE RETAIL_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE RETAIL_WH_ETL TO ROLE RETAIL_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE RETAIL_WH_XS TO ROLE RETAIL_BI_ROLE;

GRANT USAGE ON DATABASE RETAIL_DATA_PLATFORM TO ROLE RETAIL_INGEST_ROLE, RETAIL_TRANSFORM_ROLE, RETAIL_BI_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_DATA_PLATFORM TO ROLE RETAIL_INGEST_ROLE, RETAIL_TRANSFORM_ROLE, RETAIL_BI_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA RETAIL_DATA_PLATFORM.BRONZE TO ROLE RETAIL_INGEST_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK ON SCHEMA RETAIL_DATA_PLATFORM.SILVER TO ROLE RETAIL_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DATA_PLATFORM.GOLD TO ROLE RETAIL_TRANSFORM_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DATA_PLATFORM.GOLD TO ROLE RETAIL_BI_ROLE;
